### ISSUE TITLE
Liste des Pièces - Récupération des Pièces

### ISSUE THREAD

**Issue by LeMathoux** [LeMathoux/projet-csharp#10]
Création du fichier Pieces.cs dans BO
Création du fichier GestionPièces.cs dans BLL
Création du fichier PiècesDAO.cs dans DAL

Création de la classe Pièces, GestionPièces, PiècesDAO.

Création de la connexion BDD.
Ajout des Data dans le DataGridView lors du chargement du windowForm et actualisation lors de l'interaction avec le bouton.

Durée estimée : 3h
Réalisé par : Melisande

**Comment by MelisandeOnana** [comment]
Tâche terminé 
temps 2h
